### ISSUE TITLE
Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch!

### ISSUE THREAD

**Issue by ket000** [MarisElsins/getMOSPatch#32]
While downloading the patch using a proxy that uses Mcafee Gateway to intercept and examine the ssl traffic, I see intermittent issue like below. Retrying it makes it work correctly. Wondering if anything can be done to prevent this or resume the download. At least wanted to report this in case someone else is encountering the same issue. 

 Downloading C:\Users\aaa\Downloads\85724\PEOPLETOOLS-LNX-8.57.24_1of4.zip: - 29MB at average speed of 1534KB/s        Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch!
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:368)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:311)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:306)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:123)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1380)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1349)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:971)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
        at getMOSPatch.downloadFile(getMOSPatch.java:274)
        at getMOSPatch.downloadFile(getMOSPatch.java:248)
        at getMOSPatch.downloadAllFiles(getMOSPatch.java:590)
        at getMOSPatch.main(getMOSPatch.java:638)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
        at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
        at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
        at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
        at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
        at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
        at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
        at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
        at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1903)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
        ... 14 more

**Comment by MarisElsins** [comment]
Sorry, that's a kind of external factor I can't address.
